### ISSUE TITLE
Chart install fails due to postgresql in requirements.yaml

### ISSUE THREAD

**Issue by 0x234** [omisego/charts#1]
On branch `develop` with `helm install -f values.yaml .`

`Error: found in requirements.yaml, but missing in charts/ directory: postgresql`

**Comment by sirn** [comment]
It's intentional, you need to run:

```
$ helm dependency update .
```

I should mention this in README.

**Comment by 0x234** [comment]
Also (and I haven't worked with Helm dependencies before, so it may be user error):

`Error: no repository definition for https://kubernetes-charts.storage.googleapis.com/. Please add them via 'helm repo add'`

**Comment by sirn** [comment]
That's weird, the `default` repo should be [installed by default](https://github.com/helm/charts#how-do-i-install-these-charts). Can you run `helm init --client-only` and see if it works?

**Comment by 0x234** [comment]
Same error: `Error: no repository definition for https://kubernetes-charts.storage.googleapis.com/. Please add them via 'helm repo add'`

**Comment by sirn** [comment]
You probably need to add it manually with helm repo add or nuke ~/.helm. Looks like something is wrong with your Helm installation.

**Comment by 0x234** [comment]
That seems to have fixed this issue
