### ISSUE TITLE
Comparison error in deployment.yaml

### ISSUE THREAD

**Issue by 0x234** [omisego/charts#2]
This appears to be a real error unrelated to the `requirements.yaml`:

`Error: render error in "ewallet/templates/deployment.yaml": template: ewallet/templates/deployment.yaml:92:48: executing "ewallet/templates/deployment.yaml" at <ne "">: error calling ne: incompatible types for comparison`

**Comment by sirn** [comment]
Can fix for the time being with:

```
ewalletDbPoolSize: "15"
localLedgerDbPoolSize: "5"
```

…in values.yaml. This is due to YAML implicit typing.

**Comment by 0x234** [comment]
Helm hangs with no output when I provide that

**Comment by sirn** [comment]
Inspect the result of kubectl get pods, Helm is waiting for Pods to be created.

**Comment by jbunce** [comment]
`  Warning  Failed     46m (x12 over 48m)  kubelet, gke-neutrino-jp-bluedog-default-pool-cfec024b-khw8  Error: secrets "illmannered-snake-ewallet" not found`

**Comment by sirn** [comment]
The commit d7b2db8 should fix the comparison issue. You should remove the workaround from earlier comment 🙇
